### ISSUE TITLE
Invalid Info.plist merging result

### ISSUE THREAD

**Issue by ekharkunov-ms** [defold/extender#205]
**Steps to reproduce:**
1. Add Info.plist in extension section
```
<key>NSPhotoLibraryUsageDescription</key>
<string>Your application needs permission to save the content to the gallery.</string>
```
2. In main project add Info.plist with section
```
<key>NSPhotoLibraryUsageDescription</key>
<string>The game needs access to your photo gallery so you can attach screenshots to tech support requests</string>
```
3. Build project for ios.

In build log got warning:

`_WARNING: Plist overriding value for key 'NSPhotoLibraryUsageDescription': from 'The game needs access to your photo gallery so you can attach screenshots to tech support requests' to 'Your application needs permission to save the content to the gallery.'_`

In result Info.plist we got section from extension Info.plist, not from main Info.plist.

**Expected result:**
Result Info.plist should contain section from main Info.plist, not from extension Info.plist.

**Comment by JCash** [comment]
The main problem is that while Android has a way of specifying how to apply properties, the apple Info.plist doesn't.
We've tried mimicking the pattern of using a "main" info plist, and then applying the extension plists on top of it (just as it's done for Android).

The question is, how to tag the property to to not be "overridable".

The simplest approach I can see is to add another plist, that we apply last: "main plist" < "extensions plist" < "app plist"
The drawback is of course that it's fairly confusing to have _two_ plists at the app scope.

Another approach could be to add some new property system _within_ the Info.plist.
E.g. some meta properties that describe the behavior:
```
	<key>merge_NSPhotoLibraryUsageDescription</key>
	<string>keep</string>
```

It might seem trivial at a first glance, but it should also be able to handle arrays and dicts (or maybe not?)

**Comment by britzl** [comment]
> Or, perhaps it's even possible to use the Android type markup (we can remove it when building):
> 
> ```
> <key merge="keep">NSPhotoLibraryUsageDescription</key>
> ```

I like this approach!

**Comment by britzl** [comment]
Note: Update documentation when merged! https://defold.com/manuals/extensions-manifest-merge-tool/#ios--macos
