### ISSUE TITLE
[Cocoapods] Support compiler flags from pod_target_xcconfig

### ISSUE THREAD

**Issue by ekharkunov-ms** [defold/extender#270]
Some of the pod specs contains section 'pod_target_xcconfig' (for example, https://github.com/getsentry/sentry-cocoa/blob/7.31.5/Sentry.podspec#L19). 
Need to parse such sections and add flags for compiler because it can be crucial for building pod.
Some useful refs:
* https://developer.apple.com/documentation/xcode/build-settings-reference
* https://pewpewthespells.com/blog/buildsettings.html

Also note that definitions from main spec should be inherited by sub spec.

**Comment by britzl** [comment]
> Also note that definitions from main spec should be inherited by sub spec.

Moved to separate issue: https://github.com/defold/extender/issues/277
