### ISSUE TITLE
[Cocoapods] Dynamic framework doesn't pack with application

### ISSUE THREAD

**Issue by ekharkunov-ms** [defold/extender#274]
Describe the problem
Some of ios framework links with target application in "dynamic" manner. It means that application should have "Frameworks/SomeLibrary.framework" inside application bundle.

Example
1. Use podfile like
```
platform :ios, '11.0'

pod 'HelpshiftX', '10.2.3'
```
2. Add to ext.manifest following lines
```
platforms:
    arm64-ios:
        context:
            linkFlags:  ['-Wl,-rpath,@executable_path/Frameworks']
```
3. Build and run application. Get following error during luanch
```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dyld: Using shared cache: 9816A151-4D39-3378-B552-7BCA27A9DCB5 | dependent dylib '@rpath/HelpshiftX.framework/HelpshiftX' not found for '/private/var/containers/Bundle/Application/413FDAD0-9FA7-4D03-A419-2B9A9A5A2C19/sample-app.app/defoldhelpshift', tried but didn't find: '/private/var/containers/Bundle/Application/413FDAD0-9FA7-4D03-A419-2B9A9A5A2C19/sample-app.app/Frameworks/HelpshiftX.framework/HelpshiftX' '@rpath/HelpshiftX.framework/HelpshiftX' '/System/Library/Frameworks/HelpshiftX.framework/HelpshiftX'
Highlighted by Thread:  0
```

**Comment by britzl** [comment]
Hmm, it is not really clear from the Podspec that this should happen:

https://github.com/CocoaPods/Specs/blob/master/Specs/9/2/b/HelpshiftX/10.2.2/HelpshiftX.podspec.json

How do we know it is a dynamic framework and include it? Should it always be done like this?

**Comment by britzl** [comment]
https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb#L157C16-L162
