### ISSUE TITLE
Remove sha1 from ExtenderResource interface

### ISSUE THREAD

**Issue by vlaaad** [defold/extender#343]
It seems we don't use the `sha1` method of the `ExtenderResource` at all. When we need a sha1, we use `getContent` and then hash it.

**Comment by britzl** [comment]
Remember that ExtenderClient is used in Bob. Perhaps the function is used by bob somehow?

**Comment by vlaaad** [comment]
I haven't found any usages of the `sha1` method in the `ExtenderResource` implementations defined in Bob

**Comment by britzl** [comment]
ExtenderResource is subclassed here:

https://github.com/defold/defold/blob/dev/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ExtenderUtil.java#L70

But it might actually be that sha1() is not used there either. Go ahead and remove it then!
