### ISSUE TITLE
Update the "scratch" disk with more space.

### ISSUE THREAD

**Issue by JCash** [defold/extender#346]
Sometimes it fails on `CannotPullContainer` due to disk out of space.
It seems the folder `/var/lib/docker/tmp` fills up with `GetImageBlob224773415` temp files.
Due to our big container size, it comes down to luck that the images gets installed before installing the next image.

<img width="688" alt="Screenshot 2024-02-12 at 12 30 10" src="https://github.com/defold/extender/assets/1349334/e0169ff9-0eea-4dcf-b725-6ed89e22ae0e">

**Comment by ekharkunov** [comment]
Extender moved away from AWS. Obsolete.
