### ISSUE TITLE
Add cron job of cleaning up the docker unused space on AWS (extender, server)

### ISSUE THREAD

**Issue by mathiaswking** [defold/extender#359]
Occasionally we get this error, regarding the "thin pool".
It turns out AWS/Docker doesn't reclaim unused space automatically.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/CannotCreateContainerError.html

    sudo sh -c "docker ps -q | xargs docker inspect --format='{{ .State.Pid }}' | xargs -IZ fstrim /proc/Z/root/"

**Comment by ekharkunov** [comment]
Extender moved away from AWS. Obsolete.
