### ISSUE TITLE
Status page

### ISSUE THREAD

**Issue by aglitchman** [defold/extender#417]
Until today, you could go to https://build.defold.com/ and realise from the simple answer that the build server is up and running and available. Now it returns to me a 502 response, i.e. some kind of error.

I think that it is necessary to bring back at least some status page, such as ‘Hello! I'm a build server.’.

**Comment by JCash** [comment]
Yes, that is indeed the goal. It should be reincarnated soon, with an improved status (for all backend servers as well)
Currently, it's just a little work-in-progress :)

**Comment by ekharkunov** [comment]
Changes on the way https://github.com/defold/defold.github.io/pull/127

**Comment by aglitchman** [comment]
The status page on the site is a very cool thing, but I wish that simply going to https://build.defold.com/ would make it clear that the address and host is just physically available from my computer.

It's an easy way to verify that. I predict you will have million questions from people about why when you go to the build server link it returns a 502 error and ‘is it not working?’.

You can write on the root page that this is the server entrypoint, this page is not for you, and the status page is right there (link).

**Comment by ekharkunov** [comment]
Ans yes, 502 not great error code to show that "You can't access to that page". Let's say that it's an area for improvement to make HTTP response code according to real response from the server.

**Comment by AGulev** [comment]
can we redirect from https://build.defold.com/ and https://build-stage.defold.com/ to https://defold.com/extender_status/

or something like that?

**Comment by JCash** [comment]
Also, I wonder about the page name. Most services I've seen use the "status" name.
E.g. statud.defold.com or defold.com/status

What do you think?

**Comment by britzl** [comment]
> What do you think?

Yes, defold.com/status might be better tbh



> can we redirect from https://build.defold.com/ and https://build-stage.defold.com/ to https://defold.com/extender_status/

Probably yes.

**Comment by ekharkunov** [comment]
We can make a redirection to new status page. Also I'll rename it.
But also I want to make some improvements in terms of what HTTP code returns from different request to be more consistent and more informative. So the action points are:
* rename /extender_status -> /status
* make redirection from build.defold.com/build-stage.defold.com -> defold.com/status
* return correct HTTP codes for / request

**Comment by ekharkunov** [comment]
Page rename https://github.com/defold/defold.github.io/pull/129

**Comment by ekharkunov** [comment]
Now status information returns from request to '/' endpoint.
All other requests should return correct response code now.
After thinking for a while I decided not to redirect requests from '/' to 'defold.com/status' because '/status' page contains information about both server (and can contain more information about other part of infrastructure in the future) when we send request to certain server.

Close for now. Feel free to reopen if any additional discussion is needed.
