### ISSUE TITLE
The user.env doesn't handle paths with spaces.

### ISSUE THREAD

**Issue by JCash** [defold/extender#487]
When I ran `./server/scripts/standalone/setup-standalone-env.sh ` I got:

```
Load user env ...
/Users/mawe/work/extender/server/scripts/standalone/../../envs/user.env: line 16: Studio: command not found
```

It is due to the fact that the PATH contains paths with spaces in them and it isn't wrapped in ""

**Comment by JCash** [comment]
This is still an issue?
I am on `442f0e327277fd7358535367c2c86f7803cd7ea3` (Add maxFormPart configuration option for Jetty.) and it still produces the same error:
```bash
~/work/extender $ ./server/scripts/standalone/setup-standalone-env.sh                                                      [dev] 11:44:09
Load common env ...
Load user env ...
/Users/mawe/work/extender/server/scripts/standalone/../../envs/user.env: line 17: Studio: command not found
```

**Comment by JCash** [comment]
If I removed the file, and ran again, it worked twice in a row.
I guess that could be the workaround.

**Comment by ekharkunov** [comment]
Added `user.env` cleanup during generation #498
