### ISSUE TITLE
Can't build YandexMobileAds for iOS [unknown argument: '-parsed-as-library']

### ISSUE THREAD

**Issue by TinyDobbins** [defold/extender#586]
build iOS dont work for me, got this issue:

```
ERROR: extension-yandex-ads/ext.manifest:34: 'AM com.defold.manifestmergetool.InfoPlistMerger mergePlists
WARNING: Plist adding value for key 'MinimumOSVersion': '13.0''

ERROR: extension-yandex-ads/ext.manifest:0: 'unknown argument: '-parsed-as-library'
<unknown>:0: error: unknown argument: '-parsed-as-library''

ERROR: extension-yandex-ads/ext.manifest:0: 'unknown argument: '-parsed-as-library'
<unknown>:0: error: unknown argument: '-parsed-as-library''

ERROR: extension-yandex-ads/ext.manifest:0: 'unknown argument: '-parsed-as-library'
<unknown>:0: error: unknown argument: '-parsed-as-library''
```

Defold version:
![image](https://github.com/user-attachments/assets/2f64d652-a07a-46af-a367-8b90a0239f6e)

pod file:
```
platform :ios, '13.0'
pod 'YandexMobileAds', '7.2.0'
pod 'AppLovinYandexMobileAdsAdapters'
pod 'IronSourceYandexMobileAdsAdapters'
pod 'MintegralYandexMobileAdsAdapters'
```

ext.manifest:
```
name: "YandexSdkAds"

platforms:
    android:
        context:
            aaptExtraPackages: ['com.yandex.android', 'com.yandex.android.mobileads', 'com.yandex.mobile', 'com.yandex.mobile.ads', 'com.yandex.mobile.ads.imp', 'androidx.viewpager2', 'androidx.annotation', 'androidx.core', 'androidx.recyclerview', 'androidx.appcompat', 'androidx.transition', 'androidx.collection', 'androidx.appcompat.resources']

    ios:
        context:
            flags: ['-fcxx-modules', '-fmodules', '-fobjc-weak', '-Wno-module-import-in-extern-c']
            linkFlags:  ['-ObjC', '-Wl,-rpath,/usr/lib/swift', '-Wl,-rpath,@executable_path/Frameworks']
            libs:       ['swiftCompatibility51', 'swiftCompatibility50']
```

tried both build.defold.com and build-stage.defold.com

repo case:
[test_yandex.zip](https://github.com/user-attachments/files/18175841/test_yandex.zip)

logs:
[log.txt.zip](https://github.com/user-attachments/files/18175909/log.txt.zip)
[log.txt_stage.zip](https://github.com/user-attachments/files/18175910/log.txt_stage.zip)

**Comment by osov** [comment]
The same error when building on Defold 1.9.5 and 1.9.6, on both servers build.defold.com and build-stage.defold.com

**Comment by britzl** [comment]
This should be resolved in a patched 1.9.6 which I thought was released yesterday.

 @JCash and @ekharkunov ?

This is part of another fix for certain combinations of builds where the same dependency is included more than once but with different versions.

**Comment by ekharkunov** [comment]
I've made a typo in argument name. `-parsed-as-library` instead of `-parse-as-library`.

**Comment by ekharkunov** [comment]
@osov @TinyDobbins Please, update to latest 1.9.6 (56c82b2fb1ba929d85b3736d7ed1f8b522ab716a). Should work as expected.

**Comment by TinyDobbins** [comment]
@ekharkunov I haven't seen it in release version of 1.9.6, but I see this commit in 1.9.6 beta.
and yes, it works! Thanks a lot for fast fixing!!
